apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-table-script
data:
    postgres-crud.sql: |-
      \c crud-starter-api
      CREATE TABLE testtable1 (
            id serial PRIMARY KEY,
            first VARCHAR(100),
            last VARCHAR(100),
            email text UNIQUE NOT NULL,
            phone VARCHAR(100),
            location VARCHAR(100),
            hobby VARCHAR(100),
            added TIMESTAMP NOT NULL
           );