apiVersion: v1
kind: Service
metadata:
  name: crudapi-postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - name: postgresport
      port: 5432
---
    apiVersion: v1
    kind: Service
    metadata:
      name: crudapi-service
    spec:
      selector:
        app: crudapi
      type: NodePort
      ports:
        - name: httpport
          port: 5000