apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: pglocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: pglocalstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/datanew